using System.Text.Json.Serialization;
using KalshiSharp.Serialization.Converters;

namespace KalshiSharp.Models.WebSocket;

/// <summary>
/// Base class for all WebSocket responses received from Kalshi.
/// </summary>
[JsonConverter(typeof(WebSocketMessageConverter))]
public abstract record WebSocketMessage
{
    /// <summary>
    /// Message type identifier.
    /// </summary>
    [JsonPropertyName("type")]
    public abstract string Type { get; }

    /// <summary>
    /// Server-generated subscription identifier (sid) used to identify the channel.
    /// </summary>
    [JsonPropertyName("sid")]
    public int Sid { get; init; }

    /// <summary>Server-side sequence number for ordering.</summary>
    [JsonPropertyName("seq")]
    public long? Sequence { get; init; }

    /// <summary>Legacy server timestamp in Unix milliseconds.</summary>
    [JsonPropertyName("ts")]
    public long? Timestamp { get; init; }

    /// <summary>Gets the legacy timestamp as UTC.</summary>
    [JsonIgnore]
    public DateTimeOffset? TimestampUtc => Timestamp.HasValue
        ? DateTimeOffset.FromUnixTimeMilliseconds(Timestamp.Value)
        : null;
}


/// <summary>
/// Base class for all WebSocket responses received from Kalshi, which contain a message.
/// </summary>
/// <typeparam name="T">Type of message body.</typeparam>
public abstract record WebSocketMessage<T> : WebSocketMessage 
    where T: class
{
    /// <summary>
    /// Response's message payload.
    /// </summary>
    [JsonPropertyName("msg")]
    public required T Message { get; set; }
}

/// <summary>
/// Confirmation that a subscription was successful.
/// </summary>
public sealed record SubscriptionConfirmation : WebSocketMessage<SubscriptionConfirmation.MessageBody>
{
    /// <inheritdoc/>
    public override string Type => "subscribed";

    /// <summary>
    /// Unique ID of the command request. Generated by the client and should be unique within a WS session.
    /// </summary>
    public int Id { get; init; }

    /// <summary>Legacy flat channel name.</summary>
    [JsonPropertyName("channel")]
    public string? Channel { get; init; }

    /// <summary>Legacy flat market ticker list.</summary>
    [JsonPropertyName("markets")]
    public IReadOnlyList<string>? Markets { get; init; }

    public sealed record MessageBody
    {
        /// <summary>The server-assigned subscription identifier.</summary>
        [JsonPropertyName("sid")]
        public int Sid { get; init; }

        /// <summary>
        /// The channel that was subscribed to (e.g., "orderbook_delta", "trade").
        /// </summary>
        [JsonPropertyName("channel")]
        public string? Channel { get; init; }
    }
}

/// <summary>
/// Confirmation that an unsubscription was successful.
/// </summary>
public sealed record UnsubscriptionConfirmation : WebSocketMessage
{
    /// <inheritdoc/>
    public override string Type => "unsubscribed";

    /// <summary>
    /// Unique ID of the command request. Generated by the client and should be unique within a WS session.
    /// </summary>
    [JsonPropertyName("id")]
    public int Id { get; init; }

    /// <summary>
    /// Sequential number that should be checked if you want to guarantee you received all the messages. Used for snapshot/delta consistency
    /// </summary>
    [JsonIgnore]
    public int Seq
    {
        get => checked((int)(Sequence ?? 0));
        init => Sequence = value;
    }

    /// <summary>Legacy flat channel name.</summary>
    [JsonPropertyName("channel")]
    public string? Channel { get; init; }

    /// <summary>Legacy flat market ticker list.</summary>
    [JsonPropertyName("markets")]
    public IReadOnlyList<string>? Markets { get; init; }
}

/// <summary>
/// OK message from the WebSocket server.
/// </summary>
public sealed record OKMessage : WebSocketMessage
{
    /// <inheritdoc/>
    public override string Type => "ok";

    /// <summary>
    /// Unique ID of the command request. Generated by the client and should be unique within a WS session.
    /// </summary>
    [JsonPropertyName("id")]
    public int Id { get; init; }

    /// <summary>
    /// Sequential number that should be checked if you want to guarantee you received all the messages. Used for snapshot/delta consistency
    /// </summary>
    [JsonIgnore]
    public int Seq
    {
        get => checked((int)(Sequence ?? 0));
        init => Sequence = value;
    }

    /// <summary>
    /// Full list of market tickers after update
    /// </summary>
    [JsonPropertyName("market_tickers")]
    public IReadOnlyList<string>? MarketTickers { get; init; }

    /// <summary>
    /// Full list of market IDs after update.
    /// </summary>
    [JsonPropertyName("market_ids")]
    public IReadOnlyList<string>? MarketIds { get; init; }
}

/// <summary>
/// Error message from the WebSocket server.
/// </summary>
public sealed record ErrorMessage : WebSocketMessage
{
    /// <inheritdoc/>
    public override string Type => "error";

    /// <summary>Legacy error code.</summary>
    [JsonPropertyName("code")]
    public string? Code { get; init; }

    /// <summary>Legacy human-readable error message.</summary>
    [JsonPropertyName("msg")]
    public string? Message { get; init; }
}

/// <summary>Current nested error-message envelope.</summary>
public sealed record ErrorMessageV2 : WebSocketMessage<ErrorMessageV2.MessageBody>
{
    /// <inheritdoc/>
    public override string Type => "error";

    /// <summary>Unique client command identifier.</summary>
    public int Id { get; init; }

    /// <summary>Current error details.</summary>
    public sealed record MessageBody
    {
        /// <summary>
        /// Error code.
        /// </summary>
        [JsonPropertyName("code")]
        public int Code { get; init; }

        /// <summary>
        /// Human-readable error message.
        /// </summary>
        [JsonPropertyName("msg")]
        public string? ErrorMessage { get; init; }

        /// <summary>
        /// Market UUID if error is market-specific.
        /// </summary>
        [JsonPropertyName("market_id")]
        public string? MarketId { get; init; }

        /// <summary>
        /// Market ticker if error is market-specific.
        /// </summary>
        [JsonPropertyName("market_ticker")]
        public string? MarketTicker { get; init; }
    }
}
